import os
import sys
from pathlib import Path

from langchain_core.output_parsers import JsonOutputParser
from langchain_core.prompts import ChatPromptTemplate

# ---------------------------------------------------------
# Add the parent directory to Python's module search path
# ---------------------------------------------------------
# __file__ → current Python file
# resolve() → converts it to an absolute path
# parents[1] → goes two levels up in the directory structure
#
# This allows us to import modules from the parent project directory.

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


# ---------------------------------------------------------
# Import the LLM
# ---------------------------------------------------------
# This is your configured LLM object.
# For example, it could be an OpenAI Chat Model.
from llm.openAI_llm import llm


# =========================================================
# JSON OUTPUT PARSER
# =========================================================

# Create a JSON parser.
#
# The parser has two important responsibilities:
#
# 1. It can generate format instructions for the LLM.
# 2. It can parse the LLM's JSON response into a Python object.
#
# IMPORTANT:
# JsonOutputParser() by itself does NOT define a specific schema
# such as:
#
# {
#     "topic": "...",
#     "explanation": "...",
#     "key_points": [...]
# }
#
# It mainly tells the LLM to produce valid JSON.
#
JSON_parser = JsonOutputParser()


# =========================================================
# 1. DETAILED ANSWER PROMPT
# =========================================================

template_detailed = ChatPromptTemplate(
    [
        (
            "system",
            """
            Tell me about: {topic}

            {format_instructions}
            """
        )
    ],

    # -----------------------------------------------------
    # PARTIAL VARIABLES
    # -----------------------------------------------------
    # {format_instructions} is NOT provided through invoke().
    #
    # Instead, we provide it here when creating the prompt.
    #
    # JSON_parser.get_format_instructions()
    # generates instructions telling the LLM how its response
    # should be formatted.
    #
    # Conceptually, the prompt becomes something like:
    #
    # Tell me about: LangChain
    #
    # Return the output as valid JSON.
    #
    partial_variables={
        "format_instructions": JSON_parser.get_format_instructions()
    }
)


# =========================================================
# 2. SUMMARY PROMPT
# =========================================================

template_summary = ChatPromptTemplate(
    [
        (
            "human",
            """
            Summarize this data: {data}

            Return the response ONLY as valid JSON.

            {format_instructions}
            """
        )
    ],

    # Again, {format_instructions} is automatically populated
    # using the instructions generated by JsonOutputParser.
    #
    # We don't need to pass format_instructions when calling
    # chainSummary.invoke().
    #
    partial_variables={
        "format_instructions": JSON_parser.get_format_instructions()
    }
)


# =========================================================
# CHAINS
# =========================================================

# Chain 1:
#
# Prompt
#   ↓
# LLM
#   ↓
# JSON Parser
#
# The output of the prompt is sent to the LLM.
# The LLM's response is then passed to JSON_parser.
#
chainDetailed = template_detailed | llm | JSON_parser


# Chain 2:
#
# Summary Prompt
#   ↓
# LLM
#   ↓
# JSON Parser
#
chainSummary = template_summary | llm | JSON_parser


# =========================================================
# USER INPUT
# =========================================================

ques = input("What do you want to ask:\n")


if ques:

    # -----------------------------------------------------
    # DETAILED ANSWER
    # -----------------------------------------------------
    #
    # Here we provide only the runtime variable:
    #
    # {topic} → ques
    #
    # We DO NOT provide format_instructions here because
    # format_instructions was already provided using
    # partial_variables above.
    #
    detailedAnswer = chainDetailed.invoke(
        {
            "topic": ques
        }
    )


    print("\n================ DETAILED ANSWER ================\n")

    # detailedAnswer is already parsed by JsonOutputParser.
    #
    # Instead of receiving raw text like:
    #
    # '{"topic": "...", "explanation": "..."}'
    #
    # you get a Python dictionary/object.
    #
    print(detailedAnswer)


    # -----------------------------------------------------
    # SUMMARY ANSWER
    # -----------------------------------------------------
    #
    # Now we send the detailedAnswer to the summary prompt.
    #
    # {data} → detailedAnswer
    #
    # Again, we don't provide format_instructions here because
    # it was already configured through partial_variables.
    #
    summaryAnswer = chainSummary.invoke(
        {
            "data": detailedAnswer
        }
    )


    print("\n=========================>>>>>>\n")

    # summaryAnswer is also already parsed by JsonOutputParser.
    #
    print(summaryAnswer)