import os
import sys
from pathlib import Path


# ---------------------------------------------------------
# 1. Add the project's parent directory to Python's
#    module search path.
# ---------------------------------------------------------
# __file__ = path of the current Python file
# resolve() = converts it into an absolute path
# parents[1] = goes two levels up in the directory structure
#
# This allows us to import modules from other folders
# in our project.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


# ---------------------------------------------------------
# 2. Import the Pydantic Output Parser
# ---------------------------------------------------------
# PydanticOutputParser is used to convert the LLM's
# response into a Pydantic model/object.
#
# Example:
# LLM JSON response
#       ↓
# PydanticOutputParser
#       ↓
# ReviewAnalysis object
from langchain_core.output_parsers import PydanticOutputParser


# ---------------------------------------------------------
# 3. Import ChatPromptTemplate
# ---------------------------------------------------------
# ChatPromptTemplate is used to create a prompt template
# containing dynamic variables such as {review} and
# {format_instructions}.
from langchain_core.prompts import ChatPromptTemplate


# ---------------------------------------------------------
# 4. Import our Pydantic model
# ---------------------------------------------------------
# ReviewAnalysis defines the structure that we expect
# from the LLM.
#
# For example, it may contain:
# - review
# - sentiment
# - emotion
# - complaint
from structredOutput.pydantic_StructuredOutput import ReviewAnalysis


# ---------------------------------------------------------
# 5. Import the Hugging Face LLM
# ---------------------------------------------------------
# This is the language model that will analyze the
# customer review.
from llm.huggingFaceUnstructured_llm import llm


# =========================================================
# 6. Create the Pydantic Output Parser
# =========================================================
# We tell LangChain that the LLM's output should follow
# the structure defined by ReviewAnalysis.
#
# The parser will:
# 1. Read the LLM response
# 2. Parse the response
# 3. Validate it against ReviewAnalysis
# 4. Return a ReviewAnalysis object
parser = PydanticOutputParser(
    pydantic_object=ReviewAnalysis
)


# =========================================================
# 7. Generate format instructions
# =========================================================
# The parser automatically generates instructions telling
# the LLM how its response should be formatted.
#
# For example, it may generate instructions similar to:
#
# "Return a JSON object with fields such as
#  review, sentiment, emotion, complaint..."
#
# These instructions will be inserted into our prompt.
format_instructions = parser.get_format_instructions()


# =========================================================
# 8. Create the Prompt Template
# =========================================================
# {review} will be replaced by the user's review.
#
# {format_instructions} will be replaced by the formatting
# instructions generated by PydanticOutputParser.
prompt = ChatPromptTemplate.from_template(
    """
Analyze the following customer review:

{review}

{format_instructions}
"""
)


# =========================================================
# 9. Create the LangChain Pipeline
# =========================================================
#
# The | operator connects each component together.
#
# Flow:
#
# ChatPromptTemplate
#        ↓
#       LLM
#        ↓
# PydanticOutputParser
#
# The prompt creates the final prompt.
# The LLM generates the response.
# The parser converts the response into ReviewAnalysis.
chain = prompt | llm | parser


# =========================================================
# 10. Get review from the user
# =========================================================
review = input("Enter the review: ")


# =========================================================
# 11. Invoke the chain
# =========================================================
# We pass values for the variables used in our prompt:
#
# {review}
# {format_instructions}
#
# The chain then:
# 1. Creates the prompt
# 2. Sends it to the LLM
# 3. Parses the LLM response
# 4. Returns a ReviewAnalysis object
if review:

    result = chain.invoke({
        "review": review,
        "format_instructions": format_instructions
    })


    # -----------------------------------------------------
    # 12. Print the final Pydantic object
    # -----------------------------------------------------
    print(result)