import os
import sys
from pathlib import Path

# Import DuckDuckGo search tool provided by LangChain
from langchain_community.tools import DuckDuckGoSearchRun


# =========================================================
# PROJECT PATH CONFIGURATION
# =========================================================

# Get the parent directory of the current file.
# This allows us to import modules from our project structure.
current_dir = Path(__file__).resolve().parents[1]

# Add the project directory to Python's module search path.
sys.path.insert(0, str(current_dir))


# Import the LLM configuration from our project
from llm.openAI_llm import llm


# =========================================================
# CREATE THE TOOL
# =========================================================

# Create an instance of the DuckDuckGo search tool.
#
# This tool allows the LLM/application to perform
# web searches using DuckDuckGo.
searchEngine = DuckDuckGoSearchRun()


# =========================================================
# GET USER QUERY
# =========================================================

# Ask the user for a question/query.
quest = input("What is your query ?? \n")


# =========================================================
# DIRECT TOOL CALL
# =========================================================

# We could directly execute the search tool like this:
#
# result = searchEngine.invoke("What is the news today")
#
# However, we are NOT doing that here because our goal
# is to demonstrate TOOL BINDING.
#
# Direct invocation means:
#
#     Application
#          ↓
#     DuckDuckGo Tool
#          ↓
#       Result
#
# In that case, the LLM is not deciding whether to use
# the tool.


# =========================================================
# TOOL BINDING
# =========================================================

# Bind the DuckDuckGo tool to the LLM.
#
# bind_tools() tells the LLM:
#
# "You have access to this tool and you can request
#  that this tool be used when necessary."
#
# IMPORTANT:
#
# Tool binding DOES NOT execute the tool.
#
# It only makes the tool available to the LLM.
tool_binded_llm = llm.bind_tools([searchEngine])


# =========================================================
# INVOKE THE LLM
# =========================================================

# Check that the user actually entered a query.
if quest:

    # Send the user's query to the LLM.
    #
    # The LLM will analyze the query and decide whether
    # it needs to use the bound DuckDuckGo search tool.
    result = tool_binded_llm.invoke(quest)

    # Print the response generated by the LLM.
    print(result)