from pathlib import Path
import sys


# ---------------------------------------------------------
# STEP 1: Find the project root directory
# ---------------------------------------------------------

# __file__ = path of this Python file.
#
# .resolve() converts it into an absolute path.
#
# .parents[1] moves two directories upward.
#
# This allows us to find the root directory of our project.
current_dir = Path(__file__).resolve().parents[1]


# ---------------------------------------------------------
# STEP 2: Add project directory to Python's import path
# ---------------------------------------------------------

# This allows Python to find modules/packages inside
# our project directory.
#
# Without this, imports such as:
#
# from Agents.getWeather import get_weather
#
# may fail depending on where the script is executed from.
sys.path.insert(0, str(current_dir))


# ---------------------------------------------------------
# STEP 3: Import our weather tools
# ---------------------------------------------------------

# Tool 1:
# Gets the actual/current weather information for a city.
from Agents.getWeather import get_weather


# Tool 2:
# Uses the LLM to suggest activities based on the
# city and weather information.
from Agents.weatherActivityFunction import get_weather_activity


# ---------------------------------------------------------
# STEP 4: Import LangChain's agent creation function
# ---------------------------------------------------------

# create_agent creates an agent that can reason about
# the user's request and decide which tools to call.
from langchain.agents import create_agent


# ---------------------------------------------------------
# STEP 5: Create the AI Agent
# ---------------------------------------------------------

agent = create_agent(

    # Specify which LLM/model the agent should use.
    #
    # The model is responsible for:
    # - Understanding the user's request
    # - Deciding which tool to call
    # - Passing the correct arguments to the tools
    # - Combining the tool results
    # - Generating the final response
    model="openai:gpt-5.5",

    # -----------------------------------------------------
    # Give the agent access to our tools
    # -----------------------------------------------------

    tools=[
        get_weather,
        get_weather_activity
    ],

    # -----------------------------------------------------
    # System prompt
    # -----------------------------------------------------

    # This tells the agent how it should behave.
    system_prompt="""
You are a helpful weather assistant.

When the user provides a city:

1. First get the current weather for that city using get_weather.

2. Then use the weather information to suggest suitable
   activities using get_weather_activity.

3. Give the user a clear final answer.
"""
)


# ---------------------------------------------------------
# STEP 6: Ask the user for a city
# ---------------------------------------------------------

# input() pauses the program and waits for the user
# to enter a city.
city = input("Which city are you looking for? ")


# ---------------------------------------------------------
# STEP 7: Send the user's request to the agent
# ---------------------------------------------------------

result = agent.invoke(
    {
        "messages": [
            {
                "role": "user",

                # Create the user's actual question using
                # the city entered above.
                #
                # Example:
                #
                # "What is the weather in Noida and
                #  what activities can I do?"
                "content": (
                    f"What is the weather in {city} "
                    f"and what activities can I do?"
                )
            }
        ]
    }
)


# ---------------------------------------------------------
# STEP 8: Print the final response
# ---------------------------------------------------------

# The agent returns a state containing a list of messages.
#
# result["messages"][-1]
#       ↓
# Gets the last message in the conversation.
#
# .content
#       ↓
# Gets the actual text of that message.
#
# So this prints the final answer generated by the agent.
print(result["messages"][-1].content)